name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: ["main"]

jobs:

  linux-windows-build:
    name: Sign Index
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Minisign
      run: |
        MINISIGN_TMP=`mktemp -d`
        cd $MINISIGN_TMP
        wget https://github.com/aead/minisign/releases/download/v0.2.0/minisign-linux-amd64.tar.gz
        tar xvf minisign-linux-amd64.tar.gz
        mv ./minisign ~/minisign

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Sign Package
      run: |
        touch ~/minisign.key && chmod 600 ~/minisign.key
        echo -e "${{ secrets.MINISIGN_PRIVATE_KEY }}" > ~/minisign.key
        bash -c "echo \"\" | ~/minisign -s ~/minisign.key -S -m ./armory.json -x armory.minisig"

    - name: "Publish Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./armory.json
          ./armory.minisig

